

  module FreeswitchCli
    module HangupCauses

        extend self

        DEFAULT = [
            {q850_code: 0, q850_reason: "UNSPECIFIED", sip_code: 500, sip_reason: "Server Internal Error"},
            {q850_code: 1, q850_reason: "UNALLOCATED_NUMBER", sip_code: 404, sip_reason: "Not Found"},
            {q850_code: 2, q850_reason: "NO_ROUTE_TRANSIT_NET", sip_code: 404, sip_reason: "Not Found"},
            {q850_code: 3, q850_reason: "NO_ROUTE_DESTINATION", sip_code: 404, sip_reason: "Not Found"},
            {q850_code: 6, q850_reason: "CHANNEL_UNACCEPTABLE", sip_code: 406, sip_reason: "Not Acceptable"},
            {q850_code: 7, q850_reason: "CALL_AWARDED_DELIVERED", sip_code: 200, sip_reason: "OK"},
            {q850_code: 16, q850_reason: "NORMAL_CLEARING", sip_code: 200, sip_reason: "OK"},
            {q850_code: 17, q850_reason: "USER_BUSY", sip_code: 486, sip_reason: "Busy Here"},
            {q850_code: 18, q850_reason: "NO_USER_RESPONSE", sip_code: 408, sip_reason: "Request Timeout"},
            {q850_code: 19, q850_reason: "NO_ANSWER", sip_code: 480, sip_reason: "Temporarily Unavailable"},
            {q850_code: 20, q850_reason: "SUBSCRIBER_ABSENT", sip_code: 480, sip_reason: "Temporarily Unavailable"},
            {q850_code: 21, q850_reason: "CALL_REJECTED", sip_code: 603, sip_reason: "Decline"},
            {q850_code: 22, q850_reason: "NUMBER_CHANGED", sip_code: 410, sip_reason: "Gone"},
            {q850_code: 23, q850_reason: "REDIRECTION_TO_NEW_DESTINATION", sip_code: 410, sip_reason: "Gone"},
            {q850_code: 25, q850_reason: "EXCHANGE_ROUTING_ERROR", sip_code: 483, sip_reason: "Too Many Hops"},
            {q850_code: 27, q850_reason: "DESTINATION_OUT_OF_ORDER", sip_code: 502, sip_reason: "Bad Gateway"},
            {q850_code: 28, q850_reason: "INVALID_NUMBER_FORMAT", sip_code: 484, sip_reason: "Address Incomplete"},
            {q850_code: 29, q850_reason: "FACILITY_REJECTED", sip_code: 501, sip_reason: "Not Implemented"},
            {q850_code: 31, q850_reason: "NORMAL_UNSPECIFIED", sip_code: 480, sip_reason: "Temporarily Unavailable"},
            {q850_code: 34, q850_reason: "NORMAL_CIRCUIT_CONGESTION", sip_code: 503, sip_reason: "Service Unavailable"},
            {q850_code: 38, q850_reason: "NETWORK_OUT_OF_ORDER", sip_code: 503, sip_reason: "Service Unavailable"},
            {q850_code: 41, q850_reason: "NORMAL_TEMPORARY_FAILURE", sip_code: 503, sip_reason: "Service Unavailable"},
            {q850_code: 42, q850_reason: "SWITCH_CONGESTION", sip_code: 503, sip_reason: "Service Unavailable"},
            {q850_code: 44, q850_reason: "REQUESTED_CHAN_UNAVAIL", sip_code: 503, sip_reason: "Service Unavailable"},
            {q850_code: 45, q850_reason: "PRE_EMPTED", sip_code: 503, sip_reason: "Service Unavailable"},
            {q850_code: 47, q850_reason: "", sip_code: 503, sip_reason: "Service Unavailable"},
            {q850_code: 50, q850_reason: "FACILITY_NOT_SUBSCRIBED", sip_code: 406, sip_reason: "Not Acceptable"},
            {q850_code: 52, q850_reason: "OUTGOING_CALL_BARRED", sip_code: 403, sip_reason: "Forbidden"},
            {q850_code: 54, q850_reason: "INCOMING_CALL_BARRED", sip_code: 403, sip_reason: "Forbidden"},
            {q850_code: 57, q850_reason: "BEARERCAPABILITY_NOTAUTH", sip_code: 403, sip_reason: "Forbidden"},
            {q850_code: 58, q850_reason: "BEARERCAPABILITY_NOTAVAIL", sip_code: 503, sip_reason: "Service Unavailable"},
            {q850_code: 63, q850_reason: "SERVICE_UNAVAILABLE", sip_code: 503, sip_reason: "Service Unavailable"},
            {q850_code: 65, q850_reason: "BEARERCAPABILITY_NOTIMPL", sip_code: 488, sip_reason: "Not Acceptable Here"},
            {q850_code: 66, q850_reason: "CHAN_NOT_IMPLEMENTED", sip_code: 406, sip_reason: "Not Acceptable"},
            {q850_code: 69, q850_reason: "FACILITY_NOT_IMPLEMENTED", sip_code: 501, sip_reason: "Not Implemented"},
            {q850_code: 79, q850_reason: "SERVICE_NOT_IMPLEMENTED", sip_code: 501, sip_reason: "Not Implemented"},
            {q850_code: 81, q850_reason: "INVALID_CALL_REFERENCE", sip_code: 503, sip_reason: "Service Unavailable"},
            {q850_code: 88, q850_reason: "INCOMPATIBLE_DESTINATION", sip_code: 488, sip_reason: "Not Acceptable Here"},
            {q850_code: 95, q850_reason: "INVALID_MSG_UNSPECIFIED", sip_code: 488, sip_reason: "Not Acceptable Here"},
            {q850_code: 96, q850_reason: "MANDATORY_IE_MISSING", sip_code: 488, sip_reason: "Not Acceptable Here"},
            {q850_code: 97, q850_reason: "MESSAGE_TYPE_NONEXIST", sip_code: 488, sip_reason: "Not Acceptable Here"},
            {q850_code: 98, q850_reason: "WRONG_MESSAGE", sip_code: 488, sip_reason: "Not Acceptable Here"},
            {q850_code: 99, q850_reason: "IE_NONEXIST", sip_code: 488, sip_reason: "Not Acceptable Here"},
            {q850_code: 100, q850_reason: "INVALID_IE_CONTENTS", sip_code: 488, sip_reason: "Not Acceptable Here"},
            {q850_code: 101, q850_reason: "WRONG_CALL_STATE", sip_code: 488, sip_reason: "Not Acceptable Here"},
            {q850_code: 102, q850_reason: "RECOVERY_ON_TIMER_EXPIRE", sip_code: 504, sip_reason: "Server Time-out"},
            {q850_code: 103, q850_reason: "MANDATORY_IE_LENGTH_ERROR", sip_code: 488, sip_reason: "Not Acceptable Here"},
            {q850_code: 111, q850_reason: "PROTOCOL_ERROR", sip_code: 493, sip_reason: "Undecipherable"},
            {q850_code: 127, q850_reason: "INTERWORKING", sip_code: 503, sip_reason: "Service Unavailable"},
            {q850_code: 487, q850_reason: "ORIGINATOR_CANCEL", sip_code: 487, sip_reason: "Request Terminated"},
            {q850_code: 500, q850_reason: "CRASH", sip_code: 603, sip_reason: "Decline"},
            {q850_code: 501, q850_reason: "SYSTEM_SHUTDOWN", sip_code: 603, sip_reason: "Decline"},
            {q850_code: 502, q850_reason: "LOSE_RACE", sip_code: 603, sip_reason: "Decline"},
            {q850_code: 503, q850_reason: "MANAGER_REQUEST", sip_code: 603, sip_reason: "Decline"},
            {q850_code: 600, q850_reason: "BLIND_TRANSFER", sip_code: 606, sip_reason: "Not Acceptable"},
            {q850_code: 601, q850_reason: "ATTENDED_TRANSFER", sip_code: 606, sip_reason: "Not Acceptable"},
            {q850_code: 602, q850_reason: "ALLOTTED_TIMEOUT", sip_code: 603, sip_reason: "Decline"},
            {q850_code: 603, q850_reason: "USER_CHALLENGE", sip_code: 606, sip_reason: "Not Acceptable"},
            {q850_code: 604, q850_reason: "MEDIA_TIMEOUT", sip_code: 603, sip_reason: "Decline"},
            {q850_code: 605, q850_reason: "PICKED_OFF", sip_code: 606, sip_reason: "Not Acceptable"},
            {q850_code: 606, q850_reason: "USER_NOT_REGISTERED", sip_code: 606, sip_reason: "Not Acceptable"},
            {q850_code: 607, q850_reason: "PROGRESS_TIMEOUT", sip_code: 603, sip_reason: "Decline"}
        ].freeze 
        
    end
end